<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>step by step</title>

    <!-- Bootstrap Core CSS -->
    <link href="public/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Theme CSS -->
    <link href="public/css/freelancer.min.css" rel="stylesheet">
    <link href="public/css/public.css" rel="stylesheet" type="text/css">

    <!-- Custom Fonts -->
    <link href="public/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body id="page-top" class="index">
  <div id="skipnav"><a href="#maincontent">Skip to main content</a></div>
    <!-- Navigation -->
    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top navbar-custom">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="index.html">Good to Great</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li class="page-scroll">
                        <a href="admin/pages/login.html">Login in</a>
                    </li>
                    <li class="page-scroll">
                        <a href="#about">About</a>
                    </li>
                    <li class="page-scroll">
                        <a href="#contact">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
    <section>
      <div class="container">
        <div class="col-lg-8">
          <div class="post-previews">
            <? foreach($contentList as $content): ?>
              <h3><a href="content?id=<? echo $content["id"] ?>"><? echo $content["title"]  ?></a></h3>
              <div class="category text-muted"><i class="icon-tag"></i> <? echo $content["catHtml"] ?></div>
              <div class="author text-muted">by <? echo $content["username"] ?></div>
              <div class="date text-muted"><i class="icon-clock"></i> <? echo $content["date"] ?></div>
            <? endforeach?>
          </div>
          <ul class="pagination">
            <li class="page-item <? if($page->current == 1) echo "disabled" ?>">
              <a class="page-link" href="<? if($page->current > 1) {echo "/category?page=1";} else {echo "#";} ?>" disabled="">« First</a>
            </li>
            <li class="page-item <? if($page->current == 1) echo "disabled" ?>">
              <a class="page-link" href="<? if($page->current > 1) {echo "/category?page=$page->before";} else {echo "#";} ?>" disabled="">« Prev</a>
            </li>
            <li class="page-item <? if($page->current == $page->last) echo "disabled" ?>">
              <a class="page-link" href="<? if($page->current < $page->last) {echo "/category?page=$page->next";} else {echo "#";} ?>">Next »</a>
            </li>
            <li class="page-item <? if($page->current == $page->last) echo "disabled" ?>">
              <a class="page-link" href="<? if($page->current < $page->last) {echo "/category?page=$page->last";} else {echo "#";} ?>">Last »</a>
            </li>
            <li class="page-item">
              <input class="form-control pagination-input" id="pageNumber" value="<?php echo $page->current, " / ", $page->total_pages; ?>">
            </li>
            <li class="page-item">
              <a class="page-link">Go</a>
            </li>
          </ul>
        </div>
        <div class="col-lg-4">
          <div class="input-group" style="padding-top:30px;">
              <input type="text" class="form-control">
              <span class="input-group-btn">
                  <button class="btn btn-default" type="button">
                      <span class="glyphicon glyphicon-search"></span>
              </button>
              </span>
          </div>
          <div class="paddingUp" style="padding-top:30px;">
            <ul class="list-group">
              <? foreach($catList as $cat): ?>
                <li class="list-group-item justify-content-between">
                  <strong><a href="catogary/index?catId=<? echo $cat->categoryID ?>"><? echo $cat->categoryName ?></a>
                  </strong>
                  <span class="badge badge-default badge-pill"><?echo $cat->num ?></span>
                </li>
              <? endforeach ?>
            </ul>
          </div>
        </div>
      </div>
  </section>
  <!-- jQuery -->
  <script src="public/lib/jquery/jquery.min.js"></script>
  <!-- Bootstrap Core JavaScript -->
  <script src="public/lib/bootstrap/js/bootstrap.min.js"></script>
  <!-- Plugin JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
  <!-- Contact Form JavaScript -->
  <script src="public/lib/jqBootstrapValidation.js"></script>
  <script src="public/lib/ckeditor/plugins/codesnippet/lib/highlight/highlight.pack.js"></script>
  <script src="public/js/contact_me.js"></script>
  <script src="public/js/public.js"></script>
  <!-- Theme JavaScript -->
  <script src="public/lib/freelancer.min.js"></script>
</body>
</html>
