<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>step by step</title>

    <!-- Bootstrap Core CSS -->
    <link href="public/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Theme CSS -->
    <link href="public/css/freelancer.min.css" rel="stylesheet">
    <link href="public/css/public.css" rel="stylesheet" type="text/css">

    <!-- jQuery -->
    <script src="../public/lib/jquery/jquery.min.js"></script>
    <script src="../public/lib/ckeditor/ckeditor.js"></script>
    <script src="../public/lib/ckeditor/plugins/codesnippet/lib/highlight/highlight.pack.js"></script>
    <script src="../public/js/public.js"></script>

    <!-- Custom Fonts -->
    <link href="public/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<input type="hidden" id="contentID" value="<? echo $content->id ?>"/>
<div class="portfolio-modal">
    <div class="modal-content">
        <div class="close-modal" data-dismiss="modal" id="closeContent">
            <div class="lr">
                <div class="rl">
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-9">
                    <div class="modal-body">
                        <h2><? echo $content->title ?></h2>
                        <hr class="star-primary">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-9">
                    <ul class="list-inline">
                        <li>Author:
                            <strong><a href="http://startbootstrap.com"><? echo $content->username ?></a>
                            </strong>
                        </li>
                        <li>Date:
                            <strong><a href="http://startbootstrap.com"><? echo $content->date ?></a>
                            </strong>
                        </li>
                        <li>update:
                            <strong><a href="http://startbootstrap.com"><? echo $content->updateDate ?></a>
                            </strong>
                        </li>
                    </ul>
                    <ul class="list-inline">
                        <li>Category:
                            <strong><a href="http://startbootstrap.com">Start Bootstrap</a>
                            </strong>,
                            <strong><a href="http://startbootstrap.com">April 2014</a>
                            </strong>,
                            <strong><a href="http://startbootstrap.com">Web Development</a>
                            </strong>
                        </li>
                    </ul>
                </div>
                <div class="col-lg-3 leftSpace">
                  <div class="input-group">
                      <input type="text" class="form-control">
                      <span class="input-group-btn">
                          <button class="btn btn-default" type="button">
                              <span class="glyphicon glyphicon-search"></span>
                      </button>
                      </span>
                  </div>
                </div>
            </div>
            <div class="row">
              <div class="col-lg-9">
                  <div class="text-left">
                    <pre>
                      Code logic is here:
                      <code class="language-java">
                        <code class="language-java"><?echo $content->content ?></code></pre>
                      </code>
                    </pre>
                  </div>
              </div>
              <div class="col-lg-3">
                <ul class="list-group paddingUp">
                    <li class="list-group-item justify-content-between">
                      <strong><a href="http://startbootstrap.com">DP</a>
                      </strong>
                      <span class="badge badge-default badge-pill">14</span>
                    </li>
                    <li class="list-group-item justify-content-between">
                      <strong><a href="http://startbootstrap.com">DFS</a>
                      </strong>
                      <span class="badge badge-default badge-pill">2</span>
                    </li>
                    <li class="list-group-item justify-content-between">
                      <strong><a href="http://startbootstrap.com">BFS</a>
                      </strong>
                      <span class="badge badge-default badge-pill">1</span>
                    </li>
                </ul>
              </div>
            </div>
            <div class="row">
              <div class="col-lg-9">
                <button type="button" id="contentEditButton" class="btn btn-default" data-dismiss="modal"><i class="glyphicon glyphicon-pencil"></i>&nbsp;&nbsp; Edit &nbsp;</button>
                <button type="button" id="contentCloseButton" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>
              </div>
            </div>
        </div>
    </div>
</div>
<body>
</html>
